
name: Build from ZIP (APK + AAB)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unpack project ZIP
        run: unzip -q ElkotrolRemote_Studio_CI_Release_FULL_BLE_APK_AAB.zip -d appsrc

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Make gradlew executable (if present)
        run: |
          if [ -f appsrc/gradlew ]; then chmod +x appsrc/gradlew; fi

      # Build Debug APK
      - name: Build Debug APK
        run: |
          cd appsrc
          if [ -f gradlew ]; then ./gradlew assembleDebug; else gradle -p . :app:assembleDebug; fi

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: appsrc/app/build/outputs/apk/debug/*.apk

      # Build Debug AAB
      - name: Build Debug AAB
        run: |
          cd appsrc
          if [ -f gradlew ]; then ./gradlew bundleDebug; else gradle -p . :app:bundleDebug; fi

      - name: Upload Debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-aab
          path: appsrc/app/build/outputs/bundle/debug/*.aab

      # Optional: Signed Release AAB if secrets provided
      - name: Decode keystore (if provided)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Build Signed Release AAB (if secrets set)
        if: ${{ secrets.KEYSTORE_BASE64 != '' && secrets.KEYSTORE_PASSWORD != '' && secrets.KEY_ALIAS != '' && secrets.KEY_PASSWORD != '' }}
        env:
          KEYSTORE_PATH: "keystore.jks"
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd appsrc
          if [ -f gradlew ]; then ./gradlew bundleRelease; else gradle -p . :app:bundleRelease; fi

      - name: Upload Release AAB (if built)
        if: ${{ always() && hashFiles('appsrc/app/build/outputs/bundle/release/*.aab') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: appsrc/app/build/outputs/bundle/release/*.aab
