name: Build from ZIP (APK + AAB)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unpack project ZIP
        run: unzip -q ElkotrolRemote_Studio_CI_Release_FULL_BLE_APK_AAB.zip -d appsrc

      - name: Set up JDK 8  # AGP 3.5.3 wymaga Javy 8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.3"

      - name: Install Gradle 5.6.4
        run: |
          curl -L https://services.gradle.org/distributions/gradle-5.6.4-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-5.6.4/bin" >> $GITHUB_PATH

      # APK (debug)
      - name: Build Debug APK
        run: gradle -p appsrc :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: appsrc/app/build/outputs/apk/debug/*.apk

      # AAB (debug)
      - name: Build Debug AAB
        run: gradle -p appsrc :app:bundleDebug

      - name: Upload Debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-aab
          path: appsrc/app/build/outputs/bundle/debug/*.aab
