name: Build from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unpack project
        run: unzip ElkotrolRemote_Studio_CI_Release_FULL_BLE_APK_AAB.zip -d appsrc

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Debug APK
        run: cd appsrc && ./gradlew assembleDebug

      - name: Build Release AAB
        run: cd appsrc && ./gradlew bundleRelease

      - name: Upload APK & AAB
        uses: actions/upload-artifact@v3
        with:
          name: android-builds
          path: |
            appsrc/app/build/outputs/apk/debug/*.apk
            appsrc/app/build/outputs/bundle/release/*.aab
